import { CookiesConsent } from "@/components/CookiesConsent";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import Navbar from "@/components/layout/navbar";
import { Heart, Package2, ShoppingCart } from "lucide-react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase: new URL("https://aedigi.com.br/"),
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="bg-purple-800/95">
            <p className="flex  items-center  justify-between text-sm font-medium text-white mx-auto max-w-7xl py-4 px-4 sm:px-6 lg:px-8">
              <span className="select-none hidden sm:flex gap-2 items-center  justify-between">
                <ShoppingCart /> Trocas e Devoluções em até 7 dias
              </span>
              <span className="select-none flex gap-2 items-center justify-between">
                <Package2 /> Frete Grátis para todo o Brasil
              </span>
              <span className="select-none hidden sm:flex gap-2 items-center  justify-between">
                <Heart /> Satisfação Garantida ou Dinheiro de Volta
              </span>
            </p>
          </div>
          <Navbar />
          <Header />
          <Suspense>
            <main>{children}</main>
          </Suspense>
          <CookiesConsent />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
